service: with-ad-for-dash

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1 # Lambda@Edge必须部署在us-east-1
  environment:
    # 注意：Lambda@Edge不支持环境变量，这些值会在构建时被注入到代码中
    BAD_CLIENT_IP_SET: ${param:BAD_CLIENT_IP_SET, '127.0.0.1'}
    AD_CONTENT_URL: ${param:AD_CONTENT_URL, 'https://example.com/ad.mp4'}

plugins:
       - serverless-lambda-edge-pre-existing-cloudfront

functions:
  viewerRequestV2:
    handler: src/handler.handleViewerRequest
    memorySize: 128
    timeout: 5
    events:
      - preExistingCloudFront:
        # ---- Mandatory Properties -----
          distributionId: E1UZTGEU927TUF # CloudFront distribution ID you want to associate
          eventType: viewer-request # Choose event to trigger your Lambda function, which are `viewer-request`, `origin-request`, `origin-response` or `viewer-response`
          pathPattern: '*' # Specifying the CloudFront behavior
          includeBody: false # Whether including body or not within request
        # ---- Optional Property -----
          stage: dev # Specify the stage at which you want this CloudFront distribution to be updated

custom:
  deploymentBucket:
    name: ${param:DEPLOYMENT_BUCKET, 'your-deployment-bucket'}
