service: ad-m4s-function

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-1
  memorySize: 256
  timeout: 30

functions:
  modifyM4s:
    handler: src/handler.handler
    events:
      - http:
          path: modify-m4s
          method: post
